using System.CommandLine;
using Common.Cli;
using Contracts;
using Contracts.Graph;
using SyncCli.Extensions;

namespace SyncCli.Commands;
public class ProposalSaveCommand : CliCommand
{
    public ProposalSaveCommand() : base(
        "save",
        "Save a Proposal via the App Graph API",
        new Func<string, string, string, int, Task>(Call),
        new()
        {
            new Option<string>(
                new string[] { "--name", "-n" },
                getDefaultValue: () => "CLI Generated Proposal",
                description: "Proposal name"
            ),
            new Option<string>(
                new string[] { "--description", "--desc", "-d" },
                getDefaultValue: () => "A Proposal generated by the Sync CLI",
                description: "Proposal description"
            ),
            new Option<int>(
                new string[] { "--id", "-i" },
                getDefaultValue: () => 0,
                description: "Proposal ID"
            )
        }
    ) { }

    static async Task Call(string graph, string name, string description, int id)
    {
        AppGraph app = App.GetAppGraph(graph);

        Console.WriteLine($"Saving proposal {name}");

        ProposalContract? result = await app.SaveProposal(new()
        {
            Id = id,
            Name = name,
            Description = description
        });

        if (result is not null)
            Console.WriteLine($"Proposal {result.Name} successfully saved with ID {result.Id}");
    }
}